version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
      args:
        - MODE=${MODE}
        - VITE_API_MODE=${VITE_API_MODE}
        - VITE_APP_TITLE=${VITE_APP_TITLE}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
        - VITE_STRIPE_KEY=${VITE_STRIPE_KEY}
        - VITE_STRIPE_BUTTON_ID=${VITE_STRIPE_BUTTON_ID}
    ports:
      - '81:4173'
    depends_on:
      - root
    restart: always

  root:
    build:
      context: ./
      dockerfile: Dockerfile.root
      args:
        - DATABASE_URL=${DATABASE_URL}
        - CORS_ORIGIN=${CORS_ORIGIN}
        - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
        - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
        - ADMIN_ID=${ADMIN_ID}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '2001:3000'
    volumes:
      - prisma:/usr/src/apps/root/prisma/ressources
    restart: always

  widget:
    build:
      context: ./
      dockerfile: ./apps/widget/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    ports:
      - '2002:4173'
    restart: always

volumes:
  prisma:
