version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./apps/app/Dockerfile
      args:
        - MODE=${MODE}
        - VITE_API_MODE=${VITE_API_MODE}
        - VITE_APP_TITLE=${VITE_APP_TITLE}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    ports:
      - '81:4173'
    depends_on:
      - root
    networks:
      - network1
    restart: always

  root:
    build:
      context: ./
      dockerfile: ./apps/root/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - CORS_ORIGIN=${CORS_ORIGIN}
        - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
        - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
        - ADMIN_ID=${ADMIN_ID}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '2001:3000'
    volumes:
      - ./apps/root/prisma/:/apps/root/prisma/
    networks:
      - network1
    restart: always

networks:
  network1:
