version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./apps/app/Dockerfile
    environment:
      - MODE=${MODE}
      - VITE_API_MODE=${VITE_API_MODE}
      - VITE_APP_TITLE=${VITE_APP_TITLE}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}

    ports:
      - '80:4173'
    depends_on:
      - root
    networks:
      - network1
    restart: always

  root:
    build:
      context: ./
      dockerfile: ./apps/root/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '2001:3000'
    volumes:
      - ./data/db.sqlite:/prisma/ressources/dev.db
    networks:
      - network1
    restart: always

networks:
  network1:
